version: "3"

services:
  pybullet:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/root/workspace/
      - ~/dataset:/root/dataset/
      - /tmp/.X11-unix:/tmp/.X11-unix
    # runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      CUDA_VISIBLE_DEVICES: 2
    stdin_open: true
    privileged: true
